name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test_vom:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build V
        run: git clone https://github.com/vlang/v ../v && cd ../v && git checkout c97f0c5 && make
      - name: Test vom
        run: ../v/v test .